language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

services:
  - postgresql

install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

before_script:
  - psql -c 'CREATE USER dgw_test;' -U postgres
  - psql -c 'CREATE DATABASE dgw_test OWNER dgw_test;' -U postgres

script:
  - go-bindata -o bindata.go template
  - go test
